Migrate npm release to ESRP
Co-authored-by: Copilot App <223556219+Copilot@users.noreply.github.com>
Copilot-Session: 3292c9aa-ecbc-45b6-8b33-2af4cecf7620

diff --git a/.azure-pipelines/azure-pipelines-release.yml b/.azure-pipelines/azure-pipelines-release.yml
--- a/.azure-pipelines/azure-pipelines-release.yml
+++ b/.azure-pipelines/azure-pipelines-release.yml
@@ -1,12 +1,25 @@
-# Release Pipeline - Build, Test, and Release
-# This pipeline will be extended to the OneESPT template
+# Manual release pipeline: build and pack, then publish to npm through ESRP.
+name: $(Date:yyyyMMdd)$(Rev:.r)
+
 trigger: none
+pr: none
 
 parameters:
 - name: dryRun
-  displayName: 'Dry Run (test publish without actually publishing)'
+  displayName: 'Dry run (build and pack without publishing)'
   type: boolean
   default: false
+
+variables:
+- group: esrp-npm-release
+- name: EsrpMainPublisher
+  value: 'ESRPRELPACMAN'
+- name: EsrpServiceEndpointUrl
+  value: 'https://api.esrp.microsoft.com'
+- name: EsrpDomainTenantId
+  value: '975f013f-7f24-47e8-a7d3-abc4752bf346'
+- name: nodeVersion
+  value: '16.x'
 
 resources:
   repositories:
@@ -14,37 +27,38 @@ resources:
     type: git
     name: 1ESPipelineTemplates/1ESPipelineTemplates
     ref: refs/tags/release
+
 extends:
   template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
   parameters:
     settings:
       networkIsolationMode: Audit
     sdl:
-      sbom:
-        enabled: false
       sourceAnalysisPool:
         name: 1ES-ABTT-Shared-Pool
         image: abtt-windows-2025
         os: windows
-    pool:
-      name: 1ES-ABTT-Shared-Pool
-      image: abtt-ubuntu-2404
-      os: linux
     customBuildTags:
     - ES365AIMigrationTooling
     stages:
-    - stage: Build
-      displayName: Build and Prerelease
+    - stage: BuildAndPack
+      displayName: Build, test, and pack
       jobs:
-      - template: .azure-pipelines/build-template.yml@self
-      - job: PublishPrerelease
-        displayName: Publish Prerelease
-        dependsOn: BuildAndTest
-        condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), eq(variables['build.sourcebranchname'], 'master'))
+      - job: pack
+        displayName: Build and pack npm package
+        pool:
+          name: 1ES-ABTT-Shared-Pool
+          image: abtt-ubuntu-2404
+          os: linux
+        templateContext:
+          outputs:
+          - output: pipelineArtifact
+            targetPath: $(Build.ArtifactStagingDirectory)/npm-packages
+            artifactName: npm-packages
         steps:
         - task: UseNode@1
           inputs:
-            version: '16.x'
+            version: $(nodeVersion)
           displayName: Install node
         - task: NpmAuthenticate@0
           inputs:
@@ -62,71 +76,66 @@ extends:
           displayName: npm install
         - script: npm run build
           displayName: npm run build
-        - ${{ if eq(parameters.dryRun, true) }}:
-          - task: Npm@1
-            displayName: Publish azure-devops-node-api to npm (dry run)
-            inputs:
-              command: custom
-              customCommand: publish --tag prerelease --dry-run
-              workingDir: '_build'
-              publishRegistry: useExternalRegistry
-              customEndpoint: btt-npm-publish-token
-              publishEndpoint: btt-npm-publish-token
-            continueOnError: true
-        - ${{ if eq(parameters.dryRun, false) }}:
-          - task: Npm@1
-            displayName: Publish azure-devops-node-api to npm
-            inputs:
-              command: custom
-              customCommand: publish --tag prerelease
-              workingDir: '_build'
-              publishRegistry: useExternalRegistry
-              customEndpoint: btt-npm-publish-token
-              publishEndpoint: btt-npm-publish-token
-            continueOnError: true
-    - stage: Release
-      displayName: Release to Latest
-      trigger: manual
+        - script: npm run units
+          displayName: Run unit tests
+        - script: |
+            set -e
+            mkdir -p "$(Build.ArtifactStagingDirectory)/npm-packages/packages"
+            npm pack --pack-destination "$(Build.ArtifactStagingDirectory)/npm-packages/packages"
+          workingDirectory: _build
+          displayName: Pack npm package
+        - script: |
+            count=$(ls -1 "$(Build.ArtifactStagingDirectory)/npm-packages/packages"/*.tgz 2>/dev/null | wc -l)
+            echo "Found $count .tgz file(s)."
+            if [ "$count" -eq 0 ]; then
+              echo "ERROR: npm pack produced no .tgz"
+              exit 1
+            fi
+          displayName: Verify npm package exists
+        - script: |
+            set -e
+            for tgz in "$(Build.ArtifactStagingDirectory)/npm-packages/packages"/*.tgz; do
+              if tar -tzf "$tgz" | grep -E '(^|/)_manifest/'; then
+                echo "ERROR: $tgz contains an SBOM _manifest/ folder"
+                exit 1
+              fi
+            done
+          displayName: Verify SBOM is outside npm package
+
+    - stage: PublishToNpmViaESRP
+      displayName: Publish to npm via ESRP
+      dependsOn: BuildAndPack
+      condition: and(succeeded(), eq('${{ parameters.dryRun }}', 'false'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
       jobs:
-      - job: Release
-        displayName: Release to Latest
+      - job: esrp
+        displayName: Publish npm package
+        pool:
+          name: 1ES-ABTT-Shared-Pool
+          image: abtt-windows-2025
+          os: windows
+        templateContext:
+          type: releaseJob
+          isProduction: true
+          inputs:
+          - input: pipelineArtifact
+            artifactName: npm-packages
+            targetPath: $(Pipeline.Workspace)/npm-packages
         steps:
-        - checkout: self
-          clean: true
-        - task: UseNode@1
+        - task: EsrpRelease@12
+          displayName: Publish package to npm via ESRP
           inputs:
-            version: 16.x
-          displayName: Install node
-        - task: NpmAuthenticate@0
-          inputs:
-            workingFile: .npmrc
-        - script: npm install
-          displayName: npm install
-        - script: npm run build
-          displayName: npm run build
-        - bash: |
-            package_name=$(npm pkg get name version | jq -r '"\(.name)@\(.version)"')
-            echo "Package name and version: $package_name"
-            echo "##vso[task.setvariable variable=npm_package]$package_name"
-          workingDirectory: '_build'
-          displayName: Get package name and version
-        - task: Npm@1
-          displayName: Remove prerelease tag for azure-devops-node-api in Npm
-          condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), eq(variables['build.sourcebranchname'], 'master'), eq('${{ parameters.dryRun }}', 'false'))
-          inputs:
-            command: custom
-            customCommand: dist-tag remove "$(npm_package)" prerelease
-            workingDir: '_build'
-            publishRegistry: useExternalRegistry
-            customEndpoint: btt-npm-publish-token
-            publishEndpoint: btt-npm-publish-token
-        - task: Npm@1
-          displayName: Add latest tag for azure-devops-node-api in Npm
-          condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), eq(variables['build.sourcebranchname'], 'master'), eq('${{ parameters.dryRun }}', 'false'))
-          inputs:
-            command: custom
-            customCommand: dist-tag add "$(npm_package)" latest
-            workingDir: '_build'
-            publishRegistry: useExternalRegistry
-            customEndpoint: btt-npm-publish-token
-            publishEndpoint: btt-npm-publish-token
+            connectedservicename: '$(EsrpServiceConnection)'
+            usemanagedidentity: true
+            keyvaultname: '$(EsrpKeyVault)'
+            signcertname: '$(EsrpSignCert)'
+            clientid: '$(EsrpClientId)'
+            intent: 'PackageDistribution'
+            contenttype: 'npm'
+            contentsource: 'Folder'
+            folderlocation: '$(Pipeline.Workspace)/npm-packages/packages'
+            waitforreleasecompletion: true
+            owners: '$(EsrpOwners)'
+            approvers: '$(EsrpApprovers)'
+            serviceendpointurl: '$(EsrpServiceEndpointUrl)'
+            mainpublisher: '$(EsrpMainPublisher)'
+            domaintenantid: '$(EsrpDomainTenantId)'
